#!/usr/bin/env node
"use strict";
/**
 * Configuration Export Script for cross-chain-simulator
 *
 * Reads CloudFormation stack outputs and generates configuration
 * files consumable by the @near-sandbox/cross-chain-simulator NPM package
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.exportConfig = exportConfig;
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
const child_process_1 = require("child_process");
function getStackOutput(stackName, outputKey) {
    try {
        const profile = process.env.AWS_PROFILE ? `--profile ${process.env.AWS_PROFILE}` : '';
        const command = `aws cloudformation describe-stacks --stack-name ${stackName} ${profile} --query "Stacks[0].Outputs[?OutputKey=='${outputKey}'].OutputValue" --output text`;
        const output = (0, child_process_1.execSync)(command, { encoding: "utf8" }).trim();
        if (!output || output === "None") {
            throw new Error(`Output ${outputKey} not found in stack ${stackName}`);
        }
        return output;
    }
    catch (error) {
        console.error(`Error getting stack output ${outputKey} from ${stackName}:`, error);
        throw error;
    }
}
function exportConfig() {
    const stackName = "near-localnet-sync";
    console.log(`Reading outputs from stack: ${stackName}`);
    try {
        const rpcUrl = getStackOutput(stackName, "nearrpcurl");
        const networkId = getStackOutput(stackName, "nearnetworkid");
        const instanceId = getStackOutput("near-localnet-infrastructure", "nearinstanceid");
        const instancePrivateIp = getStackOutput("near-localnet-infrastructure", "nearinstanceprivateip");
        let instancePublicIp = "";
        try {
            instancePublicIp = getStackOutput("near-localnet-infrastructure", "nearinstancepublicip").replace("N/A", "");
        }
        catch (e) {
            // Public IP may not be available
        }
        const config = {
            rpcUrl,
            networkId: networkId,
            instanceId,
            instancePrivateIp,
            instancePublicIp: instancePublicIp || undefined,
        };
        // Export as JSON file (in root of lib/near, not dist/)
        // __dirname in compiled version is dist/scripts, so go up two levels to lib/near root
        const configPath = path.join(__dirname, "..", "..", "localnet-config.json");
        fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
        console.log(`✅ Configuration exported to: ${configPath}`);
        // Export as .env file for easy consumption
        const envPath = path.join(__dirname, "..", "..", ".env.localnet");
        const envContent = `# NEAR Localnet Configuration
# Generated by export-config.ts
NEAR_RPC_URL=${rpcUrl}
NEAR_NETWORK_ID=${networkId}
NEAR_INSTANCE_ID=${instanceId}
NEAR_INSTANCE_PRIVATE_IP=${instancePrivateIp}
${instancePublicIp ? `NEAR_INSTANCE_PUBLIC_IP=${instancePublicIp}` : ""}
`;
        fs.writeFileSync(envPath, envContent);
        console.log(`✅ Environment file exported to: ${envPath}`);
        // Print configuration for cross-chain-simulator
        console.log("\n📋 Configuration for cross-chain-simulator:");
        console.log(JSON.stringify(config, null, 2));
        console.log("\n💡 Usage in cross-chain-simulator:");
        console.log(`import { LocalnetConfig } from '@near-sandbox/cross-chain-simulator';`);
        console.log(`const config: LocalnetConfig = {`);
        console.log(`  rpcUrl: '${rpcUrl}',`);
        console.log(`  networkId: 'localnet',`);
        console.log(`  mpcContractId: 'v1.signer-dev.testnet',`);
        console.log(`  mpcNodes: [/* MPC endpoints */]`);
        console.log(`};`);
    }
    catch (error) {
        console.error("❌ Failed to export configuration:", error);
        process.exit(1);
    }
}
// Run if executed directly
if (require.main === module) {
    exportConfig();
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZXhwb3J0LWNvbmZpZy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbImV4cG9ydC1jb25maWcudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7QUFDQTs7Ozs7R0FLRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFnR00sb0NBQVk7QUE5RnJCLHVDQUF5QjtBQUN6QiwyQ0FBNkI7QUFDN0IsaURBQXlDO0FBVXpDLFNBQVMsY0FBYyxDQUFDLFNBQWlCLEVBQUUsU0FBaUI7SUFDeEQsSUFBSSxDQUFDO1FBQ0QsTUFBTSxPQUFPLEdBQUcsT0FBTyxDQUFDLEdBQUcsQ0FBQyxXQUFXLENBQUMsQ0FBQyxDQUFDLGFBQWEsT0FBTyxDQUFDLEdBQUcsQ0FBQyxXQUFXLEVBQUUsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDO1FBQ3RGLE1BQU0sT0FBTyxHQUFHLG1EQUFtRCxTQUFTLElBQUksT0FBTyw0Q0FBNEMsU0FBUywrQkFBK0IsQ0FBQztRQUM1SyxNQUFNLE1BQU0sR0FBRyxJQUFBLHdCQUFRLEVBQUMsT0FBTyxFQUFFLEVBQUUsUUFBUSxFQUFFLE1BQU0sRUFBRSxDQUFDLENBQUMsSUFBSSxFQUFFLENBQUM7UUFDOUQsSUFBSSxDQUFDLE1BQU0sSUFBSSxNQUFNLEtBQUssTUFBTSxFQUFFLENBQUM7WUFDL0IsTUFBTSxJQUFJLEtBQUssQ0FBQyxVQUFVLFNBQVMsdUJBQXVCLFNBQVMsRUFBRSxDQUFDLENBQUM7UUFDM0UsQ0FBQztRQUNELE9BQU8sTUFBTSxDQUFDO0lBQ2xCLENBQUM7SUFBQyxPQUFPLEtBQUssRUFBRSxDQUFDO1FBQ2IsT0FBTyxDQUFDLEtBQUssQ0FBQyw4QkFBOEIsU0FBUyxTQUFTLFNBQVMsR0FBRyxFQUFFLEtBQUssQ0FBQyxDQUFDO1FBQ25GLE1BQU0sS0FBSyxDQUFDO0lBQ2hCLENBQUM7QUFDTCxDQUFDO0FBRUQsU0FBUyxZQUFZO0lBQ2pCLE1BQU0sU0FBUyxHQUFHLG9CQUFvQixDQUFDO0lBRXZDLE9BQU8sQ0FBQyxHQUFHLENBQUMsK0JBQStCLFNBQVMsRUFBRSxDQUFDLENBQUM7SUFFeEQsSUFBSSxDQUFDO1FBQ0QsTUFBTSxNQUFNLEdBQUcsY0FBYyxDQUFDLFNBQVMsRUFBRSxZQUFZLENBQUMsQ0FBQztRQUN2RCxNQUFNLFNBQVMsR0FBRyxjQUFjLENBQUMsU0FBUyxFQUFFLGVBQWUsQ0FBQyxDQUFDO1FBQzdELE1BQU0sVUFBVSxHQUFHLGNBQWMsQ0FBQyw4QkFBOEIsRUFBRSxnQkFBZ0IsQ0FBQyxDQUFDO1FBQ3BGLE1BQU0saUJBQWlCLEdBQUcsY0FBYyxDQUFDLDhCQUE4QixFQUFFLHVCQUF1QixDQUFDLENBQUM7UUFDbEcsSUFBSSxnQkFBZ0IsR0FBRyxFQUFFLENBQUM7UUFDMUIsSUFBSSxDQUFDO1lBQ0QsZ0JBQWdCLEdBQUcsY0FBYyxDQUFDLDhCQUE4QixFQUFFLHNCQUFzQixDQUFDLENBQUMsT0FBTyxDQUFDLEtBQUssRUFBRSxFQUFFLENBQUMsQ0FBQztRQUNqSCxDQUFDO1FBQUMsT0FBTyxDQUFDLEVBQUUsQ0FBQztZQUNULGlDQUFpQztRQUNyQyxDQUFDO1FBRUQsTUFBTSxNQUFNLEdBQW1CO1lBQzNCLE1BQU07WUFDTixTQUFTLEVBQUUsU0FBdUI7WUFDbEMsVUFBVTtZQUNWLGlCQUFpQjtZQUNqQixnQkFBZ0IsRUFBRSxnQkFBZ0IsSUFBSSxTQUFTO1NBQ2xELENBQUM7UUFFRix1REFBdUQ7UUFDdkQsc0ZBQXNGO1FBQ3RGLE1BQU0sVUFBVSxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsU0FBUyxFQUFFLElBQUksRUFBRSxJQUFJLEVBQUUsc0JBQXNCLENBQUMsQ0FBQztRQUM1RSxFQUFFLENBQUMsYUFBYSxDQUFDLFVBQVUsRUFBRSxJQUFJLENBQUMsU0FBUyxDQUFDLE1BQU0sRUFBRSxJQUFJLEVBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUM5RCxPQUFPLENBQUMsR0FBRyxDQUFDLGdDQUFnQyxVQUFVLEVBQUUsQ0FBQyxDQUFDO1FBRTFELDJDQUEyQztRQUMzQyxNQUFNLE9BQU8sR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLFNBQVMsRUFBRSxJQUFJLEVBQUUsSUFBSSxFQUFFLGVBQWUsQ0FBQyxDQUFDO1FBQ2xFLE1BQU0sVUFBVSxHQUFHOztlQUVaLE1BQU07a0JBQ0gsU0FBUzttQkFDUixVQUFVOzJCQUNGLGlCQUFpQjtFQUMxQyxnQkFBZ0IsQ0FBQyxDQUFDLENBQUMsMkJBQTJCLGdCQUFnQixFQUFFLENBQUMsQ0FBQyxDQUFDLEVBQUU7Q0FDdEUsQ0FBQztRQUNNLEVBQUUsQ0FBQyxhQUFhLENBQUMsT0FBTyxFQUFFLFVBQVUsQ0FBQyxDQUFDO1FBQ3RDLE9BQU8sQ0FBQyxHQUFHLENBQUMsbUNBQW1DLE9BQU8sRUFBRSxDQUFDLENBQUM7UUFFMUQsZ0RBQWdEO1FBQ2hELE9BQU8sQ0FBQyxHQUFHLENBQUMsK0NBQStDLENBQUMsQ0FBQztRQUM3RCxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxTQUFTLENBQUMsTUFBTSxFQUFFLElBQUksRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBQzdDLE9BQU8sQ0FBQyxHQUFHLENBQUMsc0NBQXNDLENBQUMsQ0FBQztRQUNwRCxPQUFPLENBQUMsR0FBRyxDQUFDLHVFQUF1RSxDQUFDLENBQUM7UUFDckYsT0FBTyxDQUFDLEdBQUcsQ0FBQyxrQ0FBa0MsQ0FBQyxDQUFDO1FBQ2hELE9BQU8sQ0FBQyxHQUFHLENBQUMsY0FBYyxNQUFNLElBQUksQ0FBQyxDQUFDO1FBQ3RDLE9BQU8sQ0FBQyxHQUFHLENBQUMsMEJBQTBCLENBQUMsQ0FBQztRQUN4QyxPQUFPLENBQUMsR0FBRyxDQUFDLDJDQUEyQyxDQUFDLENBQUM7UUFDekQsT0FBTyxDQUFDLEdBQUcsQ0FBQyxtQ0FBbUMsQ0FBQyxDQUFDO1FBQ2pELE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUFDLENBQUM7SUFFdEIsQ0FBQztJQUFDLE9BQU8sS0FBSyxFQUFFLENBQUM7UUFDYixPQUFPLENBQUMsS0FBSyxDQUFDLG1DQUFtQyxFQUFFLEtBQUssQ0FBQyxDQUFDO1FBQzFELE9BQU8sQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFDcEIsQ0FBQztBQUNMLENBQUM7QUFFRCwyQkFBMkI7QUFDM0IsSUFBSSxPQUFPLENBQUMsSUFBSSxLQUFLLE1BQU0sRUFBRSxDQUFDO0lBQzFCLFlBQVksRUFBRSxDQUFDO0FBQ25CLENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyIjIS91c3IvYmluL2VudiBub2RlXG4vKipcbiAqIENvbmZpZ3VyYXRpb24gRXhwb3J0IFNjcmlwdCBmb3IgY3Jvc3MtY2hhaW4tc2ltdWxhdG9yXG4gKiBcbiAqIFJlYWRzIENsb3VkRm9ybWF0aW9uIHN0YWNrIG91dHB1dHMgYW5kIGdlbmVyYXRlcyBjb25maWd1cmF0aW9uXG4gKiBmaWxlcyBjb25zdW1hYmxlIGJ5IHRoZSBAbmVhci1zYW5kYm94L2Nyb3NzLWNoYWluLXNpbXVsYXRvciBOUE0gcGFja2FnZVxuICovXG5cbmltcG9ydCAqIGFzIGZzIGZyb20gXCJmc1wiO1xuaW1wb3J0ICogYXMgcGF0aCBmcm9tIFwicGF0aFwiO1xuaW1wb3J0IHsgZXhlY1N5bmMgfSBmcm9tIFwiY2hpbGRfcHJvY2Vzc1wiO1xuXG5pbnRlcmZhY2UgTG9jYWxuZXRDb25maWcge1xuICAgIHJwY1VybDogc3RyaW5nO1xuICAgIG5ldHdvcmtJZDogXCJsb2NhbG5ldFwiO1xuICAgIGluc3RhbmNlSWQ/OiBzdHJpbmc7XG4gICAgaW5zdGFuY2VQcml2YXRlSXA/OiBzdHJpbmc7XG4gICAgaW5zdGFuY2VQdWJsaWNJcD86IHN0cmluZztcbn1cblxuZnVuY3Rpb24gZ2V0U3RhY2tPdXRwdXQoc3RhY2tOYW1lOiBzdHJpbmcsIG91dHB1dEtleTogc3RyaW5nKTogc3RyaW5nIHtcbiAgICB0cnkge1xuICAgICAgICBjb25zdCBwcm9maWxlID0gcHJvY2Vzcy5lbnYuQVdTX1BST0ZJTEUgPyBgLS1wcm9maWxlICR7cHJvY2Vzcy5lbnYuQVdTX1BST0ZJTEV9YCA6ICcnO1xuICAgICAgICBjb25zdCBjb21tYW5kID0gYGF3cyBjbG91ZGZvcm1hdGlvbiBkZXNjcmliZS1zdGFja3MgLS1zdGFjay1uYW1lICR7c3RhY2tOYW1lfSAke3Byb2ZpbGV9IC0tcXVlcnkgXCJTdGFja3NbMF0uT3V0cHV0c1s/T3V0cHV0S2V5PT0nJHtvdXRwdXRLZXl9J10uT3V0cHV0VmFsdWVcIiAtLW91dHB1dCB0ZXh0YDtcbiAgICAgICAgY29uc3Qgb3V0cHV0ID0gZXhlY1N5bmMoY29tbWFuZCwgeyBlbmNvZGluZzogXCJ1dGY4XCIgfSkudHJpbSgpO1xuICAgICAgICBpZiAoIW91dHB1dCB8fCBvdXRwdXQgPT09IFwiTm9uZVwiKSB7XG4gICAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IoYE91dHB1dCAke291dHB1dEtleX0gbm90IGZvdW5kIGluIHN0YWNrICR7c3RhY2tOYW1lfWApO1xuICAgICAgICB9XG4gICAgICAgIHJldHVybiBvdXRwdXQ7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgICAgY29uc29sZS5lcnJvcihgRXJyb3IgZ2V0dGluZyBzdGFjayBvdXRwdXQgJHtvdXRwdXRLZXl9IGZyb20gJHtzdGFja05hbWV9OmAsIGVycm9yKTtcbiAgICAgICAgdGhyb3cgZXJyb3I7XG4gICAgfVxufVxuXG5mdW5jdGlvbiBleHBvcnRDb25maWcoKSB7XG4gICAgY29uc3Qgc3RhY2tOYW1lID0gXCJuZWFyLWxvY2FsbmV0LXN5bmNcIjtcbiAgICBcbiAgICBjb25zb2xlLmxvZyhgUmVhZGluZyBvdXRwdXRzIGZyb20gc3RhY2s6ICR7c3RhY2tOYW1lfWApO1xuICAgIFxuICAgIHRyeSB7XG4gICAgICAgIGNvbnN0IHJwY1VybCA9IGdldFN0YWNrT3V0cHV0KHN0YWNrTmFtZSwgXCJuZWFycnBjdXJsXCIpO1xuICAgICAgICBjb25zdCBuZXR3b3JrSWQgPSBnZXRTdGFja091dHB1dChzdGFja05hbWUsIFwibmVhcm5ldHdvcmtpZFwiKTtcbiAgICAgICAgY29uc3QgaW5zdGFuY2VJZCA9IGdldFN0YWNrT3V0cHV0KFwibmVhci1sb2NhbG5ldC1pbmZyYXN0cnVjdHVyZVwiLCBcIm5lYXJpbnN0YW5jZWlkXCIpO1xuICAgICAgICBjb25zdCBpbnN0YW5jZVByaXZhdGVJcCA9IGdldFN0YWNrT3V0cHV0KFwibmVhci1sb2NhbG5ldC1pbmZyYXN0cnVjdHVyZVwiLCBcIm5lYXJpbnN0YW5jZXByaXZhdGVpcFwiKTtcbiAgICAgICAgbGV0IGluc3RhbmNlUHVibGljSXAgPSBcIlwiO1xuICAgICAgICB0cnkge1xuICAgICAgICAgICAgaW5zdGFuY2VQdWJsaWNJcCA9IGdldFN0YWNrT3V0cHV0KFwibmVhci1sb2NhbG5ldC1pbmZyYXN0cnVjdHVyZVwiLCBcIm5lYXJpbnN0YW5jZXB1YmxpY2lwXCIpLnJlcGxhY2UoXCJOL0FcIiwgXCJcIik7XG4gICAgICAgIH0gY2F0Y2ggKGUpIHtcbiAgICAgICAgICAgIC8vIFB1YmxpYyBJUCBtYXkgbm90IGJlIGF2YWlsYWJsZVxuICAgICAgICB9XG5cbiAgICAgICAgY29uc3QgY29uZmlnOiBMb2NhbG5ldENvbmZpZyA9IHtcbiAgICAgICAgICAgIHJwY1VybCxcbiAgICAgICAgICAgIG5ldHdvcmtJZDogbmV0d29ya0lkIGFzIFwibG9jYWxuZXRcIixcbiAgICAgICAgICAgIGluc3RhbmNlSWQsXG4gICAgICAgICAgICBpbnN0YW5jZVByaXZhdGVJcCxcbiAgICAgICAgICAgIGluc3RhbmNlUHVibGljSXA6IGluc3RhbmNlUHVibGljSXAgfHwgdW5kZWZpbmVkLFxuICAgICAgICB9O1xuXG4gICAgICAgIC8vIEV4cG9ydCBhcyBKU09OIGZpbGUgKGluIHJvb3Qgb2YgbGliL25lYXIsIG5vdCBkaXN0LylcbiAgICAgICAgLy8gX19kaXJuYW1lIGluIGNvbXBpbGVkIHZlcnNpb24gaXMgZGlzdC9zY3JpcHRzLCBzbyBnbyB1cCB0d28gbGV2ZWxzIHRvIGxpYi9uZWFyIHJvb3RcbiAgICAgICAgY29uc3QgY29uZmlnUGF0aCA9IHBhdGguam9pbihfX2Rpcm5hbWUsIFwiLi5cIiwgXCIuLlwiLCBcImxvY2FsbmV0LWNvbmZpZy5qc29uXCIpO1xuICAgICAgICBmcy53cml0ZUZpbGVTeW5jKGNvbmZpZ1BhdGgsIEpTT04uc3RyaW5naWZ5KGNvbmZpZywgbnVsbCwgMikpO1xuICAgICAgICBjb25zb2xlLmxvZyhg4pyFIENvbmZpZ3VyYXRpb24gZXhwb3J0ZWQgdG86ICR7Y29uZmlnUGF0aH1gKTtcblxuICAgICAgICAvLyBFeHBvcnQgYXMgLmVudiBmaWxlIGZvciBlYXN5IGNvbnN1bXB0aW9uXG4gICAgICAgIGNvbnN0IGVudlBhdGggPSBwYXRoLmpvaW4oX19kaXJuYW1lLCBcIi4uXCIsIFwiLi5cIiwgXCIuZW52LmxvY2FsbmV0XCIpO1xuICAgICAgICBjb25zdCBlbnZDb250ZW50ID0gYCMgTkVBUiBMb2NhbG5ldCBDb25maWd1cmF0aW9uXG4jIEdlbmVyYXRlZCBieSBleHBvcnQtY29uZmlnLnRzXG5ORUFSX1JQQ19VUkw9JHtycGNVcmx9XG5ORUFSX05FVFdPUktfSUQ9JHtuZXR3b3JrSWR9XG5ORUFSX0lOU1RBTkNFX0lEPSR7aW5zdGFuY2VJZH1cbk5FQVJfSU5TVEFOQ0VfUFJJVkFURV9JUD0ke2luc3RhbmNlUHJpdmF0ZUlwfVxuJHtpbnN0YW5jZVB1YmxpY0lwID8gYE5FQVJfSU5TVEFOQ0VfUFVCTElDX0lQPSR7aW5zdGFuY2VQdWJsaWNJcH1gIDogXCJcIn1cbmA7XG4gICAgICAgIGZzLndyaXRlRmlsZVN5bmMoZW52UGF0aCwgZW52Q29udGVudCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGDinIUgRW52aXJvbm1lbnQgZmlsZSBleHBvcnRlZCB0bzogJHtlbnZQYXRofWApO1xuXG4gICAgICAgIC8vIFByaW50IGNvbmZpZ3VyYXRpb24gZm9yIGNyb3NzLWNoYWluLXNpbXVsYXRvclxuICAgICAgICBjb25zb2xlLmxvZyhcIlxcbvCfk4sgQ29uZmlndXJhdGlvbiBmb3IgY3Jvc3MtY2hhaW4tc2ltdWxhdG9yOlwiKTtcbiAgICAgICAgY29uc29sZS5sb2coSlNPTi5zdHJpbmdpZnkoY29uZmlnLCBudWxsLCAyKSk7XG4gICAgICAgIGNvbnNvbGUubG9nKFwiXFxu8J+SoSBVc2FnZSBpbiBjcm9zcy1jaGFpbi1zaW11bGF0b3I6XCIpO1xuICAgICAgICBjb25zb2xlLmxvZyhgaW1wb3J0IHsgTG9jYWxuZXRDb25maWcgfSBmcm9tICdAbmVhci1zYW5kYm94L2Nyb3NzLWNoYWluLXNpbXVsYXRvcic7YCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGBjb25zdCBjb25maWc6IExvY2FsbmV0Q29uZmlnID0ge2ApO1xuICAgICAgICBjb25zb2xlLmxvZyhgICBycGNVcmw6ICcke3JwY1VybH0nLGApO1xuICAgICAgICBjb25zb2xlLmxvZyhgICBuZXR3b3JrSWQ6ICdsb2NhbG5ldCcsYCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGAgIG1wY0NvbnRyYWN0SWQ6ICd2MS5zaWduZXItZGV2LnRlc3RuZXQnLGApO1xuICAgICAgICBjb25zb2xlLmxvZyhgICBtcGNOb2RlczogWy8qIE1QQyBlbmRwb2ludHMgKi9dYCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGB9O2ApO1xuXG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgICAgY29uc29sZS5lcnJvcihcIuKdjCBGYWlsZWQgdG8gZXhwb3J0IGNvbmZpZ3VyYXRpb246XCIsIGVycm9yKTtcbiAgICAgICAgcHJvY2Vzcy5leGl0KDEpO1xuICAgIH1cbn1cblxuLy8gUnVuIGlmIGV4ZWN1dGVkIGRpcmVjdGx5XG5pZiAocmVxdWlyZS5tYWluID09PSBtb2R1bGUpIHtcbiAgICBleHBvcnRDb25maWcoKTtcbn1cblxuZXhwb3J0IHsgZXhwb3J0Q29uZmlnLCBMb2NhbG5ldENvbmZpZyB9O1xuXG4iXX0=