#!/usr/bin/env node
"use strict";
/**
 * Configuration Export Script for cross-chain-simulator
 *
 * Reads CloudFormation stack outputs and generates configuration
 * files consumable by the @near-sandbox/cross-chain-simulator NPM package
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.exportConfig = exportConfig;
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
const child_process_1 = require("child_process");
function getStackOutput(stackName, outputKey) {
    try {
        const command = `aws cloudformation describe-stacks --stack-name ${stackName} --profile shai-sandbox-profile --query "Stacks[0].Outputs[?OutputKey=='${outputKey}'].OutputValue" --output text`;
        const output = (0, child_process_1.execSync)(command, { encoding: "utf8" }).trim();
        if (!output || output === "None") {
            throw new Error(`Output ${outputKey} not found in stack ${stackName}`);
        }
        return output;
    }
    catch (error) {
        console.error(`Error getting stack output ${outputKey} from ${stackName}:`, error);
        throw error;
    }
}
function exportConfig() {
    const stackName = "near-localnet-sync";
    console.log(`Reading outputs from stack: ${stackName}`);
    try {
        const rpcUrl = getStackOutput(stackName, "nearrpcurl");
        const networkId = getStackOutput(stackName, "nearnetworkid");
        const instanceId = getStackOutput("near-localnet-infrastructure", "nearinstanceid");
        const instancePrivateIp = getStackOutput("near-localnet-infrastructure", "nearinstanceprivateip");
        let instancePublicIp = "";
        try {
            instancePublicIp = getStackOutput("near-localnet-infrastructure", "nearinstancepublicip").replace("N/A", "");
        }
        catch (e) {
            // Public IP may not be available
        }
        const config = {
            rpcUrl,
            networkId: networkId,
            instanceId,
            instancePrivateIp,
            instancePublicIp: instancePublicIp || undefined,
        };
        // Export as JSON file
        const configPath = path.join(__dirname, "..", "localnet-config.json");
        fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
        console.log(`✅ Configuration exported to: ${configPath}`);
        // Export as .env file for easy consumption
        const envPath = path.join(__dirname, "..", ".env.localnet");
        const envContent = `# NEAR Localnet Configuration
# Generated by export-config.ts
NEAR_RPC_URL=${rpcUrl}
NEAR_NETWORK_ID=${networkId}
NEAR_INSTANCE_ID=${instanceId}
NEAR_INSTANCE_PRIVATE_IP=${instancePrivateIp}
${instancePublicIp ? `NEAR_INSTANCE_PUBLIC_IP=${instancePublicIp}` : ""}
`;
        fs.writeFileSync(envPath, envContent);
        console.log(`✅ Environment file exported to: ${envPath}`);
        // Print configuration for cross-chain-simulator
        console.log("\n📋 Configuration for cross-chain-simulator:");
        console.log(JSON.stringify(config, null, 2));
        console.log("\n💡 Usage in cross-chain-simulator:");
        console.log(`import { LocalnetConfig } from '@near-sandbox/cross-chain-simulator';`);
        console.log(`const config: LocalnetConfig = {`);
        console.log(`  rpcUrl: '${rpcUrl}',`);
        console.log(`  networkId: 'localnet',`);
        console.log(`  mpcContractId: 'v1.signer-dev.testnet',`);
        console.log(`  mpcNodes: [/* MPC endpoints */]`);
        console.log(`};`);
    }
    catch (error) {
        console.error("❌ Failed to export configuration:", error);
        process.exit(1);
    }
}
// Run if executed directly
if (require.main === module) {
    exportConfig();
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZXhwb3J0LWNvbmZpZy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbImV4cG9ydC1jb25maWcudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7QUFDQTs7Ozs7R0FLRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUE4Rk0sb0NBQVk7QUE1RnJCLHVDQUF5QjtBQUN6QiwyQ0FBNkI7QUFDN0IsaURBQXlDO0FBVXpDLFNBQVMsY0FBYyxDQUFDLFNBQWlCLEVBQUUsU0FBaUI7SUFDeEQsSUFBSSxDQUFDO1FBQ0QsTUFBTSxPQUFPLEdBQUcsbURBQW1ELFNBQVMsMkVBQTJFLFNBQVMsK0JBQStCLENBQUM7UUFDaE0sTUFBTSxNQUFNLEdBQUcsSUFBQSx3QkFBUSxFQUFDLE9BQU8sRUFBRSxFQUFFLFFBQVEsRUFBRSxNQUFNLEVBQUUsQ0FBQyxDQUFDLElBQUksRUFBRSxDQUFDO1FBQzlELElBQUksQ0FBQyxNQUFNLElBQUksTUFBTSxLQUFLLE1BQU0sRUFBRSxDQUFDO1lBQy9CLE1BQU0sSUFBSSxLQUFLLENBQUMsVUFBVSxTQUFTLHVCQUF1QixTQUFTLEVBQUUsQ0FBQyxDQUFDO1FBQzNFLENBQUM7UUFDRCxPQUFPLE1BQU0sQ0FBQztJQUNsQixDQUFDO0lBQUMsT0FBTyxLQUFLLEVBQUUsQ0FBQztRQUNiLE9BQU8sQ0FBQyxLQUFLLENBQUMsOEJBQThCLFNBQVMsU0FBUyxTQUFTLEdBQUcsRUFBRSxLQUFLLENBQUMsQ0FBQztRQUNuRixNQUFNLEtBQUssQ0FBQztJQUNoQixDQUFDO0FBQ0wsQ0FBQztBQUVELFNBQVMsWUFBWTtJQUNqQixNQUFNLFNBQVMsR0FBRyxvQkFBb0IsQ0FBQztJQUV2QyxPQUFPLENBQUMsR0FBRyxDQUFDLCtCQUErQixTQUFTLEVBQUUsQ0FBQyxDQUFDO0lBRXhELElBQUksQ0FBQztRQUNELE1BQU0sTUFBTSxHQUFHLGNBQWMsQ0FBQyxTQUFTLEVBQUUsWUFBWSxDQUFDLENBQUM7UUFDdkQsTUFBTSxTQUFTLEdBQUcsY0FBYyxDQUFDLFNBQVMsRUFBRSxlQUFlLENBQUMsQ0FBQztRQUM3RCxNQUFNLFVBQVUsR0FBRyxjQUFjLENBQUMsOEJBQThCLEVBQUUsZ0JBQWdCLENBQUMsQ0FBQztRQUNwRixNQUFNLGlCQUFpQixHQUFHLGNBQWMsQ0FBQyw4QkFBOEIsRUFBRSx1QkFBdUIsQ0FBQyxDQUFDO1FBQ2xHLElBQUksZ0JBQWdCLEdBQUcsRUFBRSxDQUFDO1FBQzFCLElBQUksQ0FBQztZQUNELGdCQUFnQixHQUFHLGNBQWMsQ0FBQyw4QkFBOEIsRUFBRSxzQkFBc0IsQ0FBQyxDQUFDLE9BQU8sQ0FBQyxLQUFLLEVBQUUsRUFBRSxDQUFDLENBQUM7UUFDakgsQ0FBQztRQUFDLE9BQU8sQ0FBQyxFQUFFLENBQUM7WUFDVCxpQ0FBaUM7UUFDckMsQ0FBQztRQUVELE1BQU0sTUFBTSxHQUFtQjtZQUMzQixNQUFNO1lBQ04sU0FBUyxFQUFFLFNBQXVCO1lBQ2xDLFVBQVU7WUFDVixpQkFBaUI7WUFDakIsZ0JBQWdCLEVBQUUsZ0JBQWdCLElBQUksU0FBUztTQUNsRCxDQUFDO1FBRUYsc0JBQXNCO1FBQ3RCLE1BQU0sVUFBVSxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsU0FBUyxFQUFFLElBQUksRUFBRSxzQkFBc0IsQ0FBQyxDQUFDO1FBQ3RFLEVBQUUsQ0FBQyxhQUFhLENBQUMsVUFBVSxFQUFFLElBQUksQ0FBQyxTQUFTLENBQUMsTUFBTSxFQUFFLElBQUksRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBQzlELE9BQU8sQ0FBQyxHQUFHLENBQUMsZ0NBQWdDLFVBQVUsRUFBRSxDQUFDLENBQUM7UUFFMUQsMkNBQTJDO1FBQzNDLE1BQU0sT0FBTyxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsU0FBUyxFQUFFLElBQUksRUFBRSxlQUFlLENBQUMsQ0FBQztRQUM1RCxNQUFNLFVBQVUsR0FBRzs7ZUFFWixNQUFNO2tCQUNILFNBQVM7bUJBQ1IsVUFBVTsyQkFDRixpQkFBaUI7RUFDMUMsZ0JBQWdCLENBQUMsQ0FBQyxDQUFDLDJCQUEyQixnQkFBZ0IsRUFBRSxDQUFDLENBQUMsQ0FBQyxFQUFFO0NBQ3RFLENBQUM7UUFDTSxFQUFFLENBQUMsYUFBYSxDQUFDLE9BQU8sRUFBRSxVQUFVLENBQUMsQ0FBQztRQUN0QyxPQUFPLENBQUMsR0FBRyxDQUFDLG1DQUFtQyxPQUFPLEVBQUUsQ0FBQyxDQUFDO1FBRTFELGdEQUFnRDtRQUNoRCxPQUFPLENBQUMsR0FBRyxDQUFDLCtDQUErQyxDQUFDLENBQUM7UUFDN0QsT0FBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsU0FBUyxDQUFDLE1BQU0sRUFBRSxJQUFJLEVBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUM3QyxPQUFPLENBQUMsR0FBRyxDQUFDLHNDQUFzQyxDQUFDLENBQUM7UUFDcEQsT0FBTyxDQUFDLEdBQUcsQ0FBQyx1RUFBdUUsQ0FBQyxDQUFDO1FBQ3JGLE9BQU8sQ0FBQyxHQUFHLENBQUMsa0NBQWtDLENBQUMsQ0FBQztRQUNoRCxPQUFPLENBQUMsR0FBRyxDQUFDLGNBQWMsTUFBTSxJQUFJLENBQUMsQ0FBQztRQUN0QyxPQUFPLENBQUMsR0FBRyxDQUFDLDBCQUEwQixDQUFDLENBQUM7UUFDeEMsT0FBTyxDQUFDLEdBQUcsQ0FBQywyQ0FBMkMsQ0FBQyxDQUFDO1FBQ3pELE9BQU8sQ0FBQyxHQUFHLENBQUMsbUNBQW1DLENBQUMsQ0FBQztRQUNqRCxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDO0lBRXRCLENBQUM7SUFBQyxPQUFPLEtBQUssRUFBRSxDQUFDO1FBQ2IsT0FBTyxDQUFDLEtBQUssQ0FBQyxtQ0FBbUMsRUFBRSxLQUFLLENBQUMsQ0FBQztRQUMxRCxPQUFPLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQyxDQUFDO0lBQ3BCLENBQUM7QUFDTCxDQUFDO0FBRUQsMkJBQTJCO0FBQzNCLElBQUksT0FBTyxDQUFDLElBQUksS0FBSyxNQUFNLEVBQUUsQ0FBQztJQUMxQixZQUFZLEVBQUUsQ0FBQztBQUNuQixDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiIyEvdXNyL2Jpbi9lbnYgbm9kZVxuLyoqXG4gKiBDb25maWd1cmF0aW9uIEV4cG9ydCBTY3JpcHQgZm9yIGNyb3NzLWNoYWluLXNpbXVsYXRvclxuICogXG4gKiBSZWFkcyBDbG91ZEZvcm1hdGlvbiBzdGFjayBvdXRwdXRzIGFuZCBnZW5lcmF0ZXMgY29uZmlndXJhdGlvblxuICogZmlsZXMgY29uc3VtYWJsZSBieSB0aGUgQG5lYXItc2FuZGJveC9jcm9zcy1jaGFpbi1zaW11bGF0b3IgTlBNIHBhY2thZ2VcbiAqL1xuXG5pbXBvcnQgKiBhcyBmcyBmcm9tIFwiZnNcIjtcbmltcG9ydCAqIGFzIHBhdGggZnJvbSBcInBhdGhcIjtcbmltcG9ydCB7IGV4ZWNTeW5jIH0gZnJvbSBcImNoaWxkX3Byb2Nlc3NcIjtcblxuaW50ZXJmYWNlIExvY2FsbmV0Q29uZmlnIHtcbiAgICBycGNVcmw6IHN0cmluZztcbiAgICBuZXR3b3JrSWQ6IFwibG9jYWxuZXRcIjtcbiAgICBpbnN0YW5jZUlkPzogc3RyaW5nO1xuICAgIGluc3RhbmNlUHJpdmF0ZUlwPzogc3RyaW5nO1xuICAgIGluc3RhbmNlUHVibGljSXA/OiBzdHJpbmc7XG59XG5cbmZ1bmN0aW9uIGdldFN0YWNrT3V0cHV0KHN0YWNrTmFtZTogc3RyaW5nLCBvdXRwdXRLZXk6IHN0cmluZyk6IHN0cmluZyB7XG4gICAgdHJ5IHtcbiAgICAgICAgY29uc3QgY29tbWFuZCA9IGBhd3MgY2xvdWRmb3JtYXRpb24gZGVzY3JpYmUtc3RhY2tzIC0tc3RhY2stbmFtZSAke3N0YWNrTmFtZX0gLS1wcm9maWxlIHNoYWktc2FuZGJveC1wcm9maWxlIC0tcXVlcnkgXCJTdGFja3NbMF0uT3V0cHV0c1s/T3V0cHV0S2V5PT0nJHtvdXRwdXRLZXl9J10uT3V0cHV0VmFsdWVcIiAtLW91dHB1dCB0ZXh0YDtcbiAgICAgICAgY29uc3Qgb3V0cHV0ID0gZXhlY1N5bmMoY29tbWFuZCwgeyBlbmNvZGluZzogXCJ1dGY4XCIgfSkudHJpbSgpO1xuICAgICAgICBpZiAoIW91dHB1dCB8fCBvdXRwdXQgPT09IFwiTm9uZVwiKSB7XG4gICAgICAgICAgICB0aHJvdyBuZXcgRXJyb3IoYE91dHB1dCAke291dHB1dEtleX0gbm90IGZvdW5kIGluIHN0YWNrICR7c3RhY2tOYW1lfWApO1xuICAgICAgICB9XG4gICAgICAgIHJldHVybiBvdXRwdXQ7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgICAgY29uc29sZS5lcnJvcihgRXJyb3IgZ2V0dGluZyBzdGFjayBvdXRwdXQgJHtvdXRwdXRLZXl9IGZyb20gJHtzdGFja05hbWV9OmAsIGVycm9yKTtcbiAgICAgICAgdGhyb3cgZXJyb3I7XG4gICAgfVxufVxuXG5mdW5jdGlvbiBleHBvcnRDb25maWcoKSB7XG4gICAgY29uc3Qgc3RhY2tOYW1lID0gXCJuZWFyLWxvY2FsbmV0LXN5bmNcIjtcbiAgICBcbiAgICBjb25zb2xlLmxvZyhgUmVhZGluZyBvdXRwdXRzIGZyb20gc3RhY2s6ICR7c3RhY2tOYW1lfWApO1xuICAgIFxuICAgIHRyeSB7XG4gICAgICAgIGNvbnN0IHJwY1VybCA9IGdldFN0YWNrT3V0cHV0KHN0YWNrTmFtZSwgXCJuZWFycnBjdXJsXCIpO1xuICAgICAgICBjb25zdCBuZXR3b3JrSWQgPSBnZXRTdGFja091dHB1dChzdGFja05hbWUsIFwibmVhcm5ldHdvcmtpZFwiKTtcbiAgICAgICAgY29uc3QgaW5zdGFuY2VJZCA9IGdldFN0YWNrT3V0cHV0KFwibmVhci1sb2NhbG5ldC1pbmZyYXN0cnVjdHVyZVwiLCBcIm5lYXJpbnN0YW5jZWlkXCIpO1xuICAgICAgICBjb25zdCBpbnN0YW5jZVByaXZhdGVJcCA9IGdldFN0YWNrT3V0cHV0KFwibmVhci1sb2NhbG5ldC1pbmZyYXN0cnVjdHVyZVwiLCBcIm5lYXJpbnN0YW5jZXByaXZhdGVpcFwiKTtcbiAgICAgICAgbGV0IGluc3RhbmNlUHVibGljSXAgPSBcIlwiO1xuICAgICAgICB0cnkge1xuICAgICAgICAgICAgaW5zdGFuY2VQdWJsaWNJcCA9IGdldFN0YWNrT3V0cHV0KFwibmVhci1sb2NhbG5ldC1pbmZyYXN0cnVjdHVyZVwiLCBcIm5lYXJpbnN0YW5jZXB1YmxpY2lwXCIpLnJlcGxhY2UoXCJOL0FcIiwgXCJcIik7XG4gICAgICAgIH0gY2F0Y2ggKGUpIHtcbiAgICAgICAgICAgIC8vIFB1YmxpYyBJUCBtYXkgbm90IGJlIGF2YWlsYWJsZVxuICAgICAgICB9XG5cbiAgICAgICAgY29uc3QgY29uZmlnOiBMb2NhbG5ldENvbmZpZyA9IHtcbiAgICAgICAgICAgIHJwY1VybCxcbiAgICAgICAgICAgIG5ldHdvcmtJZDogbmV0d29ya0lkIGFzIFwibG9jYWxuZXRcIixcbiAgICAgICAgICAgIGluc3RhbmNlSWQsXG4gICAgICAgICAgICBpbnN0YW5jZVByaXZhdGVJcCxcbiAgICAgICAgICAgIGluc3RhbmNlUHVibGljSXA6IGluc3RhbmNlUHVibGljSXAgfHwgdW5kZWZpbmVkLFxuICAgICAgICB9O1xuXG4gICAgICAgIC8vIEV4cG9ydCBhcyBKU09OIGZpbGVcbiAgICAgICAgY29uc3QgY29uZmlnUGF0aCA9IHBhdGguam9pbihfX2Rpcm5hbWUsIFwiLi5cIiwgXCJsb2NhbG5ldC1jb25maWcuanNvblwiKTtcbiAgICAgICAgZnMud3JpdGVGaWxlU3luYyhjb25maWdQYXRoLCBKU09OLnN0cmluZ2lmeShjb25maWcsIG51bGwsIDIpKTtcbiAgICAgICAgY29uc29sZS5sb2coYOKchSBDb25maWd1cmF0aW9uIGV4cG9ydGVkIHRvOiAke2NvbmZpZ1BhdGh9YCk7XG5cbiAgICAgICAgLy8gRXhwb3J0IGFzIC5lbnYgZmlsZSBmb3IgZWFzeSBjb25zdW1wdGlvblxuICAgICAgICBjb25zdCBlbnZQYXRoID0gcGF0aC5qb2luKF9fZGlybmFtZSwgXCIuLlwiLCBcIi5lbnYubG9jYWxuZXRcIik7XG4gICAgICAgIGNvbnN0IGVudkNvbnRlbnQgPSBgIyBORUFSIExvY2FsbmV0IENvbmZpZ3VyYXRpb25cbiMgR2VuZXJhdGVkIGJ5IGV4cG9ydC1jb25maWcudHNcbk5FQVJfUlBDX1VSTD0ke3JwY1VybH1cbk5FQVJfTkVUV09SS19JRD0ke25ldHdvcmtJZH1cbk5FQVJfSU5TVEFOQ0VfSUQ9JHtpbnN0YW5jZUlkfVxuTkVBUl9JTlNUQU5DRV9QUklWQVRFX0lQPSR7aW5zdGFuY2VQcml2YXRlSXB9XG4ke2luc3RhbmNlUHVibGljSXAgPyBgTkVBUl9JTlNUQU5DRV9QVUJMSUNfSVA9JHtpbnN0YW5jZVB1YmxpY0lwfWAgOiBcIlwifVxuYDtcbiAgICAgICAgZnMud3JpdGVGaWxlU3luYyhlbnZQYXRoLCBlbnZDb250ZW50KTtcbiAgICAgICAgY29uc29sZS5sb2coYOKchSBFbnZpcm9ubWVudCBmaWxlIGV4cG9ydGVkIHRvOiAke2VudlBhdGh9YCk7XG5cbiAgICAgICAgLy8gUHJpbnQgY29uZmlndXJhdGlvbiBmb3IgY3Jvc3MtY2hhaW4tc2ltdWxhdG9yXG4gICAgICAgIGNvbnNvbGUubG9nKFwiXFxu8J+TiyBDb25maWd1cmF0aW9uIGZvciBjcm9zcy1jaGFpbi1zaW11bGF0b3I6XCIpO1xuICAgICAgICBjb25zb2xlLmxvZyhKU09OLnN0cmluZ2lmeShjb25maWcsIG51bGwsIDIpKTtcbiAgICAgICAgY29uc29sZS5sb2coXCJcXG7wn5KhIFVzYWdlIGluIGNyb3NzLWNoYWluLXNpbXVsYXRvcjpcIik7XG4gICAgICAgIGNvbnNvbGUubG9nKGBpbXBvcnQgeyBMb2NhbG5ldENvbmZpZyB9IGZyb20gJ0BuZWFyLXNhbmRib3gvY3Jvc3MtY2hhaW4tc2ltdWxhdG9yJztgKTtcbiAgICAgICAgY29uc29sZS5sb2coYGNvbnN0IGNvbmZpZzogTG9jYWxuZXRDb25maWcgPSB7YCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGAgIHJwY1VybDogJyR7cnBjVXJsfScsYCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGAgIG5ldHdvcmtJZDogJ2xvY2FsbmV0JyxgKTtcbiAgICAgICAgY29uc29sZS5sb2coYCAgbXBjQ29udHJhY3RJZDogJ3YxLnNpZ25lci1kZXYudGVzdG5ldCcsYCk7XG4gICAgICAgIGNvbnNvbGUubG9nKGAgIG1wY05vZGVzOiBbLyogTVBDIGVuZHBvaW50cyAqL11gKTtcbiAgICAgICAgY29uc29sZS5sb2coYH07YCk7XG5cbiAgICB9IGNhdGNoIChlcnJvcikge1xuICAgICAgICBjb25zb2xlLmVycm9yKFwi4p2MIEZhaWxlZCB0byBleHBvcnQgY29uZmlndXJhdGlvbjpcIiwgZXJyb3IpO1xuICAgICAgICBwcm9jZXNzLmV4aXQoMSk7XG4gICAgfVxufVxuXG4vLyBSdW4gaWYgZXhlY3V0ZWQgZGlyZWN0bHlcbmlmIChyZXF1aXJlLm1haW4gPT09IG1vZHVsZSkge1xuICAgIGV4cG9ydENvbmZpZygpO1xufVxuXG5leHBvcnQgeyBleHBvcnRDb25maWcsIExvY2FsbmV0Q29uZmlnIH07XG5cbiJdfQ==