#!/usr/bin/env node
/**
 * Configuration Export Script for cross-chain-simulator
 * 
 * Reads CloudFormation stack outputs and generates configuration
 * files consumable by the @near-sandbox/cross-chain-simulator NPM package
 */

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";

interface LocalnetConfig {
    rpcUrl: string;
    networkId: "localnet";
    instanceId?: string;
    instancePrivateIp?: string;
    instancePublicIp?: string;
}

function getStackOutput(stackName: string, outputKey: string): string {
    try {
        const command = `aws cloudformation describe-stacks --stack-name ${stackName} --profile shai-sandbox-profile --query "Stacks[0].Outputs[?OutputKey=='${outputKey}'].OutputValue" --output text`;
        const output = execSync(command, { encoding: "utf8" }).trim();
        if (!output || output === "None") {
            throw new Error(`Output ${outputKey} not found in stack ${stackName}`);
        }
        return output;
    } catch (error) {
        console.error(`Error getting stack output ${outputKey} from ${stackName}:`, error);
        throw error;
    }
}

function exportConfig() {
    const stackName = "near-localnet-sync";
    
    console.log(`Reading outputs from stack: ${stackName}`);
    
    try {
        const rpcUrl = getStackOutput(stackName, "nearrpcurl");
        const networkId = getStackOutput(stackName, "nearnetworkid");
        const instanceId = getStackOutput("near-localnet-infrastructure", "nearinstanceid");
        const instancePrivateIp = getStackOutput("near-localnet-infrastructure", "nearinstanceprivateip");
        let instancePublicIp = "";
        try {
            instancePublicIp = getStackOutput("near-localnet-infrastructure", "nearinstancepublicip").replace("N/A", "");
        } catch (e) {
            // Public IP may not be available
        }

        const config: LocalnetConfig = {
            rpcUrl,
            networkId: networkId as "localnet",
            instanceId,
            instancePrivateIp,
            instancePublicIp: instancePublicIp || undefined,
        };

        // Export as JSON file
        const configPath = path.join(__dirname, "..", "localnet-config.json");
        fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
        console.log(`✅ Configuration exported to: ${configPath}`);

        // Export as .env file for easy consumption
        const envPath = path.join(__dirname, "..", ".env.localnet");
        const envContent = `# NEAR Localnet Configuration
# Generated by export-config.ts
NEAR_RPC_URL=${rpcUrl}
NEAR_NETWORK_ID=${networkId}
NEAR_INSTANCE_ID=${instanceId}
NEAR_INSTANCE_PRIVATE_IP=${instancePrivateIp}
${instancePublicIp ? `NEAR_INSTANCE_PUBLIC_IP=${instancePublicIp}` : ""}
`;
        fs.writeFileSync(envPath, envContent);
        console.log(`✅ Environment file exported to: ${envPath}`);

        // Print configuration for cross-chain-simulator
        console.log("\n📋 Configuration for cross-chain-simulator:");
        console.log(JSON.stringify(config, null, 2));
        console.log("\n💡 Usage in cross-chain-simulator:");
        console.log(`import { LocalnetConfig } from '@near-sandbox/cross-chain-simulator';`);
        console.log(`const config: LocalnetConfig = {`);
        console.log(`  rpcUrl: '${rpcUrl}',`);
        console.log(`  networkId: 'localnet',`);
        console.log(`  mpcContractId: 'v1.signer-dev.testnet',`);
        console.log(`  mpcNodes: [/* MPC endpoints */]`);
        console.log(`};`);

    } catch (error) {
        console.error("❌ Failed to export configuration:", error);
        process.exit(1);
    }
}

// Run if executed directly
if (require.main === module) {
    exportConfig();
}

export { exportConfig, LocalnetConfig };

